const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');

test('video workflow, player, and assets are wired into the classic-script shell', () => {
    const index = read('index.html');
    const app = read('js/video-app.js');
    assert.match(index, /id="videoTab"[\s\S]*data-mode="video"/);
    assert.match(index, /id="videoSourceFile"[^>]*accept="\.mp4,video\/mp4"/);
    assert.match(index, /id="videoArchiveFile"[^>]*accept="\.emp4,application\/vnd\.ecryptees\.emp4"/);
    const videoPanel = index.slice(index.indexOf('id="videoPanel"'), index.indexOf('</section>', index.indexOf('id="videoPanel"')));
    assert.doesNotMatch(videoPanel, /type="password"|videoPassword/i);
    assert.match(index, /id="assetTypeVideoButton"[^>]*>视频 /);
    assert.match(index, /id="videoAssetPlayer"[^>]*playsinline/);
    assert.doesNotMatch(index, /id="videoAssetPlayer"[^>]*\scontrols(?:\s|>)/);
    assert.match(index, /id="videoExportProgressDialog"/);
    assert.match(index, /class="video-action-sheet-dialog"[^>]*id="videoAssetMenuDialog"/);
    assert.match(index, /id="videoAssetRenameForm"/);
    assert.match(index, /id="videoAssetDeleteConfirm"/);
    assert.match(index, /id="videoSeekBackwardButton"/);
    assert.match(index, /id="videoPlaybackRate"/);
    assert.match(index, /id="videoFullscreenButton"/);
    assert.match(index, /id="videoTimeline"/);
    assert.match(index, /id="videoEpisodeDrawer"/);
    assert.match(index, /id="videoEpisodeGroups"/);
    assert.match(index, /id="videoEpisodeList"/);
    assert.match(index, /id="decryptCurrentVideoButton"[^>]*>导出原 MP4</);
    assert.ok(index.indexOf('src="js/video-core.js"') < index.indexOf('src="js/video-assets.js"'));
    assert.ok(index.indexOf('src="js/video-assets.js"') < index.indexOf('src="js/video-app.js"'));
    assert.match(app, /encryptVideoButton/);
    assert.match(app, /ecryptees-open-video-archive/);
    assert.match(app, /persistBlobInPage/);
    assert.match(app, /importArchiveInPage/);
    assert.match(app, /decryptArchiveBlobInPage/);
    assert.match(app, /location\.protocol === 'file:'/);
    assert.match(app, /exportOriginalMp4/);
    assert.match(app, /exportEmp4/);
    assert.match(app, /ensureCapacity/);
    assert.match(app, /commitVideoAsset/);
    assert.match(app, /playbackPosition/);
    assert.match(app, /const poster = actionButton\('', 'play'/);
    assert.doesNotMatch(app, /actionButton\('播放', 'play'/);
    assert.match(app, /async function switchPlayerAsset/);
    assert.match(app, /setEpisodeDrawerOpen/);
    assert.match(app, /showVideoSheetView/);
    assert.doesNotMatch(app, /prompt\('修改视频名称'|prompt\('新建视频分组'/);
    assert.match(app, /new Worker\('js\/video-worker\.js'\)/);
    assert.doesNotMatch(app, /prepareBrowserPlayback|prepareAndroidPlayback|prepareFallbackPlayback/);
    assert.doesNotMatch(app, /KEY_MODE_PASSWORD|videoPassword|passwordRequest/);
});

test('video worker keeps archive conversion bounded while assets store original MP4 files', () => {
    const worker = read('js/video-worker.js');
    const videoCore = read('js/video-core.js');
    const assets = read('js/video-assets.js');
    assert.match(worker, /Math\.min\(2, Number\(payload\.parallelism\)/);
    assert.match(worker, /file\.slice\([\s\S]*format\.CHUNK_SIZE/);
    assert.match(worker, /videoCrypto\.encryptChunk/);
    assert.match(worker, /videoCrypto\.decryptChunk/);
    assert.match(worker, /createWritable\(\)/);
    assert.match(worker, /sha256-tree-v1:/);
    assert.match(worker, /ContentFingerprinter/);
    assert.doesNotMatch(assets, /\bblob\s*[:,]/);
    assert.match(assets, /opfsName/);
    assert.match(assets, /ecryptees-video-asset-/);
    assert.match(assets, /storageFormat: 'plain-mp4'/);
    assert.match(assets, /\.mp4`/);
    assert.match(assets, /function legacyAssetFileName[\s\S]*\.emp4`/);
    assert.match(assets, /removeStoredFile/);
    assert.match(assets, /DATABASE_VERSION = 3/);
    assert.match(assets, /byContentId/);
    assert.match(assets, /playbackPosition/);
    assert.doesNotMatch(worker, /PBKDF|KEY_MODE_PASSWORD|password/i);
    assert.doesNotMatch(videoCore, /PBKDF|KEY_MODE_PASSWORD|password/i);
});

test('raw asset playback no longer registers encrypted Service Worker sessions', () => {
    const app = read('js/video-app.js');
    const serviceWorker = read('service-worker.js');
    assert.match(app, /URL\.createObjectURL\(context\.file\)/);
    assert.doesNotMatch(app, /emp4-register-session|context\.headerBytes|context\.rawKey/);
    const shell = serviceWorker.slice(serviceWorker.indexOf('const APP_SHELL'), serviceWorker.indexOf('];') + 2);
    assert.doesNotMatch(shell, /\.emp4|__emp4__/);
    assert.doesNotMatch(serviceWorker, /emp4-register-session|serveEncryptedVideo|VIDEO_ROUTE_PREFIX/);
});

test('Android accepts .emp4 and exposes native AES-GCM Range playback', () => {
    const manifest = read('android-app/app/src/main/AndroidManifest.xml');
    const activity = read('android-app/app/src/main/java/com/ecryptees/offline/MainActivity.java');
    const bridge = read('js/android-bridge.js');
    assert.match(manifest, /application\/vnd\.ecryptees\.emp4/);
    assert.match(manifest, /android:pathPattern="\.\*\\\\\.emp4"/);
    assert.match(activity, /beginEmp4Playback/);
    assert.match(activity, /writeEmp4PlaybackChunk/);
    assert.match(activity, /AES\/GCM\/NoPadding/);
    assert.match(activity, /new Emp4RangeInputStream/);
    assert.match(activity, /\(header\[9\] & 0xFF\) != 0/);
    assert.match(activity, /partial \? 206 : 200/);
    assert.match(activity, /Content-Range/);
    assert.match(activity, /releaseAllEmp4Playbacks/);
    assert.match(activity, /setVideoPlaybackActive/);
    assert.match(activity, /onShowCustomView/);
    assert.match(bridge, /EcrypteesAndroidVideo/);
    assert.match(bridge, /ecryptees-open-video-archive/);
    assert.match(bridge, /768 \* 1024/);
});
